### ISSUE TITLE
Could cachelib use Apache Thrift instead of FBThrift?

### ISSUE THREAD

**Issue by yiguolei** [facebook/CacheLib#103]
We want to use CacheLib with apache arrow, but CacheLib depends on FBThrift while Apache Arrow depends on Apache Thrift. There is duplicate symbol error during link, like this:

ld.lld: error: duplicate symbol: apache::thrift::transport::TSocket::peek()

I think it is better to depend on Apache Thrift so that many apps could use it. 
Am I right?

**Comment by agordon** [comment]
Hello @yiguolei ,

Putting aside "right" vs "wrong" here, CacheLib is a facebook(/meta) project, and ThriftFB is heavily used by many FB projects (both internal and open source) - so that is not likely to change.

Regardless, you raise a good point about potentially conflicting symbols, let me see if I can reproduce this and come up with a work-around.

**Comment by yiguolei** [comment]
Hello @agordon,

Any ideas on this?

**Comment by sathyaphoenix** [comment]
@yiguolei  it is holiday period and most of us are out. Stay tuned for any updates from @agordon once we all return back in 2022.
