### ISSUE TITLE
FAQ RocksDB vs Cachelib

### ISSUE THREAD

**Issue by gaowayne** [facebook/CacheLib#108]
why FB did not add cache logic inside RocksDB, instead create another CacheLib. both are K-V interface. what is the best practice for these two products.

**Comment by 1a1a11a** [comment]
I am not a Facebook employee, but my view on having KV store and KV cache as two separate components:
1. RocksDB are optimized for writes, not reads, while Cachelib is optimized for reads. 
2. RocksDB and Cachelib have different features sets, which allows different optimizations. For example, not having to provide strong durability guarantee and range request feature allow performance improvement (no WAL, no need to maintain data in sorted order, etc.). 
3. in terms of deployments, a cache is deployed in front of a store, which means a cache sees more read traffic, while store sees more write traffic. Moreover, because store like RocksDB requires strong consistency (consensus), durability guarantee, it is usually deployed/replicated on multiple nodes with consensus algorithms like Raft. While cache can be used/deployed as either in-application library or distributed cache (like Memcached). Furthermore, cachelib can be deployed as DRAM only, KV store usually won't be deployed as DRAM only due to high cost of DRAM and difficulty of achieving durability with DRAM. 
4. in terms of working set, key-value stores like RocksDB usually acts as the source of truth and requires provisioning sufficient storage capacity to hold all the data, while caching is used to speed up serving and there is no need to store the whole working set. In other works, the capacity usage of KV store grows _much_ faster than KV cache, which means coupling the two into one library does not make sense.

**Comment by gaowayne** [comment]
@1a1a11a thank you so much man, this is very clear!

**Comment by sathyaphoenix** [comment]
@gaowayne  Juncheng covered the main reasons why CacheLib and RocksDB are two separate libraries. One thing I would add is that database storage engine's primary table stake is durability of data that is written. This is not the case for caches which by nature can evict data as more are added. This difference in expectation is leveraged in the design of both the libraries to exploit the best of other constraints and optimizing the read performance for caching and write performance and feature set for storage engines.
