### ISSUE TITLE
Centos build is failing

### ISSUE THREAD

**Issue by therealgymmy** [facebook/CacheLib#149]
Centos build is failing

It complains about not able to download metadata for repo AppStream

```
Run dnf update -y
Failed to download metadata for repo 'AppStream'
CentOS-8 - AppStream                            1[4](https://github.com/facebook/CacheLib/runs/7136228295?check_suite_focus=true#step:3:5)1  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'AppStream'
Error: Process completed with exit code 1.
```

Link: https://github.com/facebook/CacheLib/runs/7136228295?check_suite_focus=true#step:3:8

**Comment by therealgymmy** [comment]
@agordon

**Comment by agordon** [comment]
CentOS now builds successfully (e.g.
https://github.com/facebook/CacheLib/actions/runs/3021263333
https://github.com/facebook/CacheLib/actions/runs/3021907548 ).

The "AppStream" repo issue was fixed with:
https://github.com/facebook/CacheLib/blob/main/.github/workflows/build-cachelib-centos-8-5.yml#L31
