### ISSUE TITLE
Config of in-memory cache when using NVM cache

### ISSUE THREAD

**Issue by wenhaocs** [facebook/CacheLib#170]
When using navy cache / NVM cache, we need to create a in-memory cache as well for read performance. Can you provide guidance on the in-memory cache config, e.g., size, bucket/lock power? Generally, what's the role of in-memory part of the NVM cache, and how would it affect the performance? Thanks!

**Comment by jiayuebao** [comment]
@wenhaocs: 
> Can you provide guidance on the in-memory cache config, e.g., size, bucket/lock power

If you are using the HybridCache, it is actually DRAM + NVM cache instead of NVM cache only. For DRAM part, you can follow the same configuration as DRAM-only cache https://cachelib.org/docs/Cache_Library_User_Guides/Set_up_a_simple_cache. 
You should come up with a reasonable RAM cache size and configure the bucket/lock power based on https://cachelib.org/docs/Cache_Library_User_Guides/Configure_HashTable. 

> what's the role of in-memory part of the NVM cache, and how would it affect the performance

Actually, the question should be "the role of in-memory part of HybridCache". For HybridCache, each item will be inserted into DRAM cache first; when RAM is full, the item will be evicted from DRAM and inserted to NVM cache. Some NVM cache metadata will also be stored in DRAM cache.  You can check https://cachelib.org/docs/Cache_Library_Architecture_Guide/hybrid_cache to understand more. 

Users typically choose to use HybridCache because they need more storage and can tolerate not fast-enough speed.

**Comment by wenhaocs** [comment]
Thanks! Generally speaking, the hybrid cache is used to extend the DRAM cache into NVM media. In this case, we can generally follow the DRAM cache configuration as you specified: https://cachelib.org/docs/Cache_Library_User_Guides/Configure_HashTable.

However, what if we use NVM cache as the extension of a third-party DRAM cache, e.g. using Hybrid cache as the Rocksdb secondary cache? In this case, the major function we look for is the NVM part of the hybrid cache. Then, what's the role of DRAM part here? How should we configure it?

**Comment by jiayuebao** [comment]
> what if we use NVM cache as the extension of a third-party DRAM cache, e.g. using Hybrid cache as the Rocksdb secondary cache

As I've mentioned, cachelib does not support NVM-only cache.  If you want NVM cache to play a larger role, you can set a very small cache size for DRAM cache.  The role of DRAM cache is still the same as my previous comment: items will be  inserted into DRAM cache first; when DRAM is full, some items will be evicted to NVM cache (based on your eviction policy). NVM cache metadata will also be stored in DRAM cache.  If DRAM cache is quite small, most items will be loaded into nvm cache. That being said, operations like lookup are mostly happen in nvmCache. 

BTW, I think Rocksdb secondary cache is using cachelib already. Better check whether they've open sourced this part.

**Comment by wenhaocs** [comment]
It's not open sourced yet. If I understand correctly, when the dram cache is very small, the configuration of  buckets power and lock power does not matter any more, since almost all data are in Navy, right? DRAM just acts as buffer when promoting data from secondary cache to primary block cache.

**Comment by jiayuebao** [comment]
Yep, you can understand it in this way. 

And actually I found RocksDB secondary cache has open sourced here: https://github.com/facebook/CacheLib/blob/main/cachelib/adaptor/rocks_secondary_cache/CachelibWrapper.h.

**Comment by wenhaocs** [comment]
Ah I see! I though it would be open sourced from rocksdb repo. Thanks!
