### ISSUE TITLE
The NVM cache size is increasing quickly when using findToWrite(key, true) function so that the data is evicted unexpectedly.

### ISSUE THREAD

**Issue by random618** [facebook/CacheLib#178]
We need to frequently update the value of the key so that we use findToWrite function to invalidate nvm, but the ssd size is rising rapidly. Even though we set the max nvm size of 100G, the ssd is full easily and data is evicted unexpectedly. we use the default nvm config, Is there anything wrong?

**Comment by jaesoo-fb** [comment]
Hi. Could you clarify what you meant by "the ssd size is rising rapidly"? 

If you meant the NVM cache size, NVM cache size is fixed at the initialization and could not be changed. Also, if the NVM cache is full, no matter how much the space contains the live data, the NVM cache needs to perform the reclaims during which some items could be evicted or reinserted (depending on user provided policy).

**Comment by jiayuebao** [comment]
Hi @random618: If you are going to frequently update the keys, we don't recommend using `findToWrite` API for nvm-cache use case as it will be a blocking API. 

You can try the following workaround as [the comment](https://github.com/facebook/CacheLib/blob/main/cachelib/allocator/CacheAllocator.h#L537-L551) suggested:
```
auto readHandle = cache->find("my key");
if (!readHandle.isReady()) {
auto sf = std::move(readHandle)
   .toSemiFuture()
   .defer([] (auto readHandle)) {
   return std::move(readHandle).toWriteHandle();
  }
}
```

However, as what @jaesoo-fb said, this should only affect the lookup speed instead of increasing the ssd size. Hope to understand more on this part as well.

**Comment by random618** [comment]
> Hi. Could you clarify what you meant by "the ssd size is rising rapidly"?
> 
> If you meant the NVM cache size, NVM cache size is fixed at the initialization and could not be changed. Also, if the NVM cache is full, no matter how much the space contains the live data, the NVM cache needs to perform the reclaims during which some items could be evicted or reinserted (depending on user provided policy).

Sorry, I mean the nvm cache size. Concretely, I initialize nvm cache size as follows:

`navyConfig.setSimpleFile("/data/mycache", 100 * 1024 * 1024 * 1024LL, false);`

In our scenario, we use RangeMap structure. So when inserting data into RangeMap, we use the following code:

`auto handle = cache->findToWrite(key, true);
  if (handle) {
    RangeMap map = RangeMap::fromItemHandle(*cache, std::move(handle));
    map.insertOrReplace(mapKey, mapValue);
  }
`
After running for a period of time, the size of the file '/data/mycache' increased quickly from 0 to 100G and some data is unexpectedly lost in one day. Before, we only use 16G memory without nvm cache but data can exist at least one day.

We want to use nvm cache to reduce cost, but it seems that we need more nvm cache size than memory so that data will not be easily lost in one day.

**Comment by jaesoo-fb** [comment]
> We want to use nvm cache to reduce cost, but it seems that we need more nvm cache size than memory so that data will not be easily lost in one day.

Actually, as you know, cachelib is a cache, but not a persistent storage. An item can be evicted at any time. There are several hooks like the admission policy, reinsertion policy, and destuctor callback; see [Configure_HybridCache](https://cachelib.org/docs/Cache_Library_User_Guides/Configure_HybridCache) 

However, please note that this usecase might not be well supported since this is apart from cachelib's design philosophy and intended use.
