### ISSUE TITLE
Transactional Guarantees

### ISSUE THREAD

**Issue by vitruvvius** [facebook/CacheLib#179]
Thanks for a great library.

What transactional guarantees does cachelib provide for a local process,
under the assumption the next batch of inserts is <<<< total size of the cache.

Reading the docs, I would presume
(i) single-threaded process, ie serial read/write workload => linearizability 
(ii) multi-threaded process, ie parallel read/write workload => ???

**Comment by jaesoo-fb** [comment]
Hi. The cachelib is thread-safe. However, this does not mean the cachelib provides any transactional support.

We expect the client to implement any required serialization mechanism, particularly, on top of the atomicity of inserts or replaces for immutable workload. I.e., even if we don't support any cachelib-level CAS operation of mutable workload, the client can implements the CAS utilizing the feature that the `insertOrReplace()` is an atomic operation inserting or *replacing* the item with the given key in the cache.

Does this answer your question?

**Comment by vitruvvius** [comment]
the lack of transactional support answers my question,
__compare_and_swap assumes one previously had the value,
thereby stale read + write racey

we'll have to implement an internal coordinator!

**Comment by jaesoo-fb** [comment]
Oh, actually, I meant the internal coordinator at the application would be the way to go. For example, the application can implement a lock for coordinating the writes. Since `insertOrReplace()` is an atomic operation, the application can perform atomic swap using the `insertOrReplace()` after modifying the contents under the lock in another memory allocated from the cachelib. In this case, please note that existing readers could still see the old contents until they drop the old handles.

For the native support for CAS at cachelib level, I am skeptical to adding it since the cachelib is a caching engine instead of some transactional storage.

**Comment by vitruvvius** [comment]
definitely!
i adore the design,
leave it to the programmer,
more optionality.
it should stay a storage engine,
and the best storage engine :)

thanks for the help!
